CREATE DATABASE IF NOT EXISTS burgers_db;
USE burgers_db;
CREATE TABLE burgers (
    ID INT NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(255) NOT NULL,
    devoured BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (ID)
);